Migrate to GithubActions

diff --git a/Oyafile b/Oyafile
--- a/Oyafile
+++ b/Oyafile
@@ -12,7 +12,7 @@ Ignore:
 
 develop.Doc: Install development prerequisites.
 develop: |
-  go get github.com/cucumber/godog/cmd/godog
+  go get github.com/cucumber/godog/cmd/godog@v0.9.0
 
 install.Doc: Install oya.
 install: |
@@ -48,19 +48,18 @@ testKeysRemove: |
     echo "Oya test PGP Key deleted"
   fi
 
-release: |
+build-dist.Doc: Builds binaries for different archs.
+build-dist: |
+  set -e
   go get -u github.com/mitchellh/gox
-  go get -u github.com/tcnksm/ghr
-  gox -os="linux darwin" -arch="amd64 386" -output="dist/oya_${CIRCLE_TAG}_{{.OS}}_{{.Arch}}" -ldflags="-X main.buildVersion=${CIRCLE_TAG}"
-  # Windows compilation is seperated because it failes when bulding two arch parallel.
-  gox -os="windows" -arch="amd64" -output="dist/oya_${CIRCLE_TAG}_{{.OS}}_{{.Arch}}" -ldflags="-X main.buildVersion=${CIRCLE_TAG}"
-  gox -os="windows" -arch="386" -output="dist/oya_${CIRCLE_TAG}_{{.OS}}_{{.Arch}}" -ldflags="-X main.buildVersion=${CIRCLE_TAG}"
+
+  # # Windows compilation is seperated because it failes when bulding two arch parallel.
+  gox -os="linux darwin" -arch="amd64 386" -output="dist/oya_${GITHUB_REF_NAME}_{{.OS}}_{{.Arch}}" -ldflags="-X main.buildVersion=${GITHUB_REF_NAME}"
+  gox -os="windows" -arch="amd64" -output="dist/oya_${GITHUB_REF_NAME}_{{.OS}}_{{.Arch}}" -ldflags="-X main.buildVersion=${GITHUB_REF_NAME}"
+  gox -os="windows" -arch="386" -output="dist/oya_${GITHUB_REF_NAME}_{{.OS}}_{{.Arch}}" -ldflags="-X main.buildVersion=${GITHUB_REF_NAME}"
+
   find ./dist -type f ! -name "*.exe" -exec gzip {} \;
   find ./dist -type f -name "*.exe" -execdir zip {}.zip {} \;
   find ./dist -type f -name "*.exe" -exec rm {} \;
-  sha256sum dist/oya_${CIRCLE_TAG}_{darwin,linux,windows}_* | tee dist/oya_${CIRCLE_TAG}_SHA256SUMS
-  if [ "$CIRCLE_TAG" ]; then
-    ghr -t $GITHUB_TOKEN -u $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME --replace $CIRCLE_TAG dist/
-  else
-    echo "The build is missing Git / CircleCi Tag"
-  fi
+
+  sha256sum dist/oya_*_{darwin,linux,windows}_* | tee dist/oya_SHA256SUMS
